/**
 * Recommended Verdaccio config for running the full e2e-cli battery,
 * printed by `verdaccio-e2e --print-config`. It is what the consuming repos'
 * CI jobs and scripts/run-e2e.sh feed to `verdaccio --config`:
 *
 *   - max_body_size raised so scenario:tarballs can publish ~30 MB packages
 *     (Verdaccio's default is 10mb)
 *   - an `e2emock` uplink + `e2e-uplink-*` package pattern wired to the mock
 *     uplink server that scenario:uplink-failure starts on E2E_UPLINK_PORT
 *     (short timeout so the "slow uplink" case completes quickly; high
 *     max_fails so simulated failures don't trip the circuit breaker for
 *     later sub-tests)
 *   - NO npmjs uplink: the whole suite publishes every package it consumes,
 *     so the registry under test never talks to the outside world and the
 *     battery runs fully offline (and deterministically in CI)
 *
 * Relative paths (storage/htpasswd) resolve next to the config file, so write
 * it into a disposable directory.
 */
export const DEFAULT_UPLINK_PORT = 4874;

export function buildE2EConfig(uplinkPort: number = DEFAULT_UPLINK_PORT): string {
  return `# Generated by @verdaccio/e2e-cli --print-config
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 1000
web:
  enable: true
  title: Verdaccio E2E
max_body_size: 100mb
uplinks:
  e2emock:
    url: http://localhost:${uplinkPort}/
    timeout: 3s
    retry: 0
    max_fails: 100
    fail_timeout: 1s
packages:
  'e2e-uplink-*':
    access: $all
    proxy: e2emock
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
log: { type: stdout, format: pretty, level: warn }
`;
}
