name: Rust

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust:
    if: github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.nvmrc'
      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: corepack
        run: corepack enable
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm --filter @verdaccio/e2e-cli build
      - name: Format
        run: pnpm rust:fmt
      - name: Clippy
        run: pnpm rust:clippy
      - name: Docs
        run: pnpm rust:docs
