name: Rust

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust:
    if: github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: '.nvmrc'
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: corepack
        run: corepack enable
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm --filter @verdaccio/e2e-cli build
      - name: Format
        run: pnpm rust:fmt
      - name: Clippy
        run: pnpm rust:clippy
      - name: Docs
        run: pnpm rust:docs
